### ISSUE TITLE
Trait resolution for variadic arguments in Bevy

### ISSUE THREAD

**Issue by alice-i-cecile** [weiznich/rust-foundation-community-grant#3]
Original issue: https://github.com/bevyengine/bevy/issues/1519

This seems quite similar to the issue described for `tealr` [here](https://www.reddit.com/r/rust/comments/vu768z/comment/ifbwp8x/?utm_source=share&utm_medium=web2x&context=3).

**Comment by weiznich** [comment]
Thanks, I've copied the test case linked in this thread in ab2bb38cf8addabdae28e4626115cafa12b8bfe1

**Comment by alice-i-cecile** [comment]
Awesome thanks!
