### ISSUE TITLE
native-tls error messages from underlying c library

### ISSUE THREAD

**Issue by 1Dragoon** [weiznich/rust-foundation-community-grant#5]
Not sure whether this is in scope as it's not exactly a trait heavy issue (I think, I haven't gone through the source yet) but I remember this one bothering me pretty bad when I ran into it:

https://github.com/sfackler/rust-native-tls/issues/228

One reason this one can be potential trouble is that the errors in this crate will vary depending on the OS. Feel free to close if this isn't what you're looking for.

**Comment by weiznich** [comment]
Thanks for raising this issue here. The described error seems to be a linker error rather than an error emitted by rustc. Such errors are unfortunately not in the scope of my planed work.
